// BetaDeps clean-room re-implementation. MIT, copyright 2026 Maxfield
// Management Group.
//
// Generated-prefab gate.
//
// Bannerlord 1.2+ ships code-generated prefabs (Modules\<X>\bin\...\
// *.GauntletUI.AutoGenerated*.dll). When a movie / prefab has a generated
// variant, GauntletMovie.Load instantiates it via
// GeneratedPrefabContext.InstantiatePrefab and NEVER calls
// WidgetPrefab.LoadFrom(path). Our prefab patcher (WidgetPrefabHook) works by
// redirecting the XML file path LoadFrom reads -- so for generated prefabs it
// is bypassed entirely and the patch silently never applies. This is why a
// [PrefabExtension] targeting a generated prefab such as "EncyclopediaHeroPage"
// (e.g. the Courier (Messenger) mod's "Send Messenger" button) produced no
// visible change even though the mod's ViewModel mixin attached fine.
//
// Fix (the same approach upstream Bannerlord.UIExtenderEx takes): when any
// enabled module has registered a prefab patch, force GauntletMovie.Load down
// the XML path by setting its `doNotUseGeneratedPrefabs` argument to true. The
// movie -- and every nested sub-prefab it pulls in via WidgetFactory.GetCustomType
// (which is XML-only) -- then loads from XML, where WidgetPrefabHook can inject.
// Cost is the per-movie XML parse the generated prefabs were optimizing away;
// that is exactly how every UIExtenderEx-modded install has always run.

using System;
using System.Linq;
using System.Reflection;
using System.Threading;

using BetaDeps.Foundation;

using HarmonyLib;

namespace Bannerlord.UIExtenderEx.Runtime;

internal static class GeneratedPrefabGate
{
    private const string Tag = "GeneratedPrefabGate";
    private const string HarmonyId = "betadeps.uiextenderex.genprefabgate";
    private static int _installed;

    public static void Install()
    {
        if (Interlocked.CompareExchange(ref _installed, 1, 0) != 0) return;
        try
        {
            var movieType = ReflectionUtils.ResolveTypeByFullName("TaleWorlds.GauntletUI.Data.GauntletMovie");
            if (movieType == null)
            {
                DiagLog.Log(Tag, "TaleWorlds.GauntletUI.Data.GauntletMovie not found; generated-prefab gate disabled (patches on generated prefabs won't apply)");
                return;
            }

            // static IGauntletMovie Load(UIContext, WidgetFactory, string movieName,
            //   IViewModel datasource, bool doNotUseGeneratedPrefabs, bool hotReloadEnabled)
            var load = movieType
                .GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static)
                .FirstOrDefault(m => m.Name == "Load"
                    && m.GetParameters().Any(p => p.ParameterType == typeof(bool)
                        && string.Equals(p.Name, "doNotUseGeneratedPrefabs", StringComparison.Ordinal)));
            if (load == null)
            {
                DiagLog.Log(Tag, "GauntletMovie.Load(...,doNotUseGeneratedPrefabs,...) overload not found; gate disabled");
                return;
            }

            var harmony = new HarmonyLib.Harmony(HarmonyId);
            harmony.Patch(load, prefix: new HarmonyMethod(typeof(GeneratedPrefabGate), nameof(LoadPrefix)));
            DiagLog.Log(Tag, "installed prefix on GauntletMovie.Load (forces XML path so prefab patches reach generated prefabs)");
        }
        catch (Exception ex)
        {
            DiagLog.LogCaught(Tag, "Install", ex);
        }
    }

    /// <summary>
    /// Force the XML movie path whenever any enabled module registered a prefab
    /// patch. `ref` so the change reaches the real parameter the method body reads.
    /// Gated on Prefabs.Count so a setup with zero UI-patching mods keeps the
    /// generated-prefab fast path untouched.
    /// </summary>
    public static void LoadPrefix(ref bool doNotUseGeneratedPrefabs)
    {
        try
        {
            if (doNotUseGeneratedPrefabs) return;
            if (UIExtenderEngine.Enabled.Any(r => r.Prefabs.Count > 0))
                doNotUseGeneratedPrefabs = true;
        }
        catch { /* never break movie loading */ }
    }
}
