// ModReady clean-room re-implementation. MIT, copyright 2026 Maxfield
// Management Group.
//
// Generated-prefab gate.
//
// Bannerlord 1.2+ ships code-generated prefabs (Modules\<X>\bin\...\
// *.GauntletUI.AutoGenerated*.dll). When a movie / prefab has a generated
// variant, GauntletMovie.Load instantiates it via
// GeneratedPrefabContext.InstantiatePrefab and NEVER calls
// WidgetPrefab.LoadFrom(path). Our prefab patcher (WidgetPrefabHook) works by
// redirecting the XML file path LoadFrom reads -- so for generated prefabs it
// is bypassed entirely and the patch silently never applies. This is why a
// [PrefabExtension] targeting a generated prefab such as "EncyclopediaHeroPage"
// (e.g. the Courier (Messenger) mod's "Send Messenger" button) produced no
// visible change even though the mod's ViewModel mixin attached fine.
//
// Fix (the same approach upstream Bannerlord.UIExtenderEx takes): when any
// enabled module has registered a prefab patch, force GauntletMovie.Load down
// the XML path by setting its `doNotUseGeneratedPrefabs` argument to true. The
// movie -- and every nested sub-prefab it pulls in via WidgetFactory.GetCustomType
// (which is XML-only) -- then loads from XML, where WidgetPrefabHook can inject.
// Cost is the per-movie XML parse the generated prefabs were optimizing away;
// that is exactly how every UIExtenderEx-modded install has always run.

using System;
using System.Linq;
using System.Reflection;
using System.Threading;

using ModReady.Foundation;

using HarmonyLib;

namespace Bannerlord.UIExtenderEx.Runtime;

internal static class GeneratedPrefabGate
{
    private const string Tag = "GeneratedPrefabGate";
    private const string HarmonyId = "modready.uiextenderex.genprefabgate";
    private static int _installed;
    private static bool _anyPrefabPatch;

    public static void Install()
    {
        if (Interlocked.CompareExchange(ref _installed, 1, 0) != 0) return;
        try
        {
            var movieType = ReflectionUtils.ResolveTypeByFullName("TaleWorlds.GauntletUI.Data.GauntletMovie");
            if (movieType == null)
            {
                DiagLog.Log(Tag, "TaleWorlds.GauntletUI.Data.GauntletMovie not found; generated-prefab gate disabled (patches on generated prefabs won't apply)");
                return;
            }

            // static IGauntletMovie Load(UIContext, WidgetFactory, string movieName,
            //   IViewModel datasource, bool doNotUseGeneratedPrefabs, bool hotReloadEnabled)
            var load = movieType
                .GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static)
                .FirstOrDefault(m => m.Name == "Load"
                    && m.GetParameters().Any(p => p.ParameterType == typeof(bool)
                        && string.Equals(p.Name, "doNotUseGeneratedPrefabs", StringComparison.Ordinal)));
            if (load == null)
            {
                DiagLog.Log(Tag, "GauntletMovie.Load(...,doNotUseGeneratedPrefabs,...) overload not found; gate disabled");
                return;
            }

            var harmony = new HarmonyLib.Harmony(HarmonyId);
            harmony.Patch(load, prefix: new HarmonyMethod(typeof(GeneratedPrefabGate), nameof(LoadPrefix)));
            DiagLog.Log(Tag, "installed prefix on GauntletMovie.Load (forces XML path so prefab patches reach generated prefabs)");

            // S4 fix: also force the engine-global generated-prefab switch so
            // NESTED generated sub-prefabs (e.g. the clan/party screens' injected
            // widgets) load from XML too. The Load argument alone only covers the
            // top-level movie; nested prefabs read this global getter directly,
            // which is the lever upstream UIExtenderEx pulls ("disable AutoGens
            // globally"). Getter confirmed: TaleWorlds.Engine.NativeConfig
            // .GetUIDoNotUseGeneratedPrefabs (static bool property).
            var cfgType = ReflectionUtils.ResolveTypeByFullName("TaleWorlds.Engine.NativeConfig");
            var cfgGetter = cfgType?.GetProperty("GetUIDoNotUseGeneratedPrefabs",
                                BindingFlags.Public | BindingFlags.Static)?.GetGetMethod(true);
            if (cfgGetter != null)
            {
                harmony.Patch(cfgGetter, postfix: new HarmonyMethod(typeof(GeneratedPrefabGate), nameof(ConfigPostfix)));
                DiagLog.Log(Tag, "installed postfix on NativeConfig.GetUIDoNotUseGeneratedPrefabs (covers nested generated prefabs)");
            }
            else
            {
                DiagLog.Log(Tag, "NativeConfig.GetUIDoNotUseGeneratedPrefabs not found; nested generated prefabs may bypass patches");
            }
        }
        catch (Exception ex)
        {
            DiagLog.LogCaught(Tag, "Install", ex);
        }
    }

    /// <summary>
    /// Force the XML movie path whenever any enabled module registered a prefab
    /// patch. `ref` so the change reaches the real parameter the method body reads.
    /// Gated on Prefabs.Count so a setup with zero UI-patching mods keeps the
    /// generated-prefab fast path untouched.
    /// </summary>
    public static void LoadPrefix(ref bool doNotUseGeneratedPrefabs)
    {
        try
        {
            if (doNotUseGeneratedPrefabs) return;
            if (UIExtenderEngine.Enabled.Any(r => r.Prefabs.Count > 0))
                doNotUseGeneratedPrefabs = true;
        }
        catch { /* never break movie loading */ }
    }

    /// <summary>
    /// Postfix on the engine-global NativeConfig.GetUIDoNotUseGeneratedPrefabs
    /// getter. The Load-argument prefix only forces the TOP-LEVEL movie onto the
    /// XML path; nested generated sub-prefabs (the clan/party screens' injected
    /// widgets) read this global switch directly. Forcing it true whenever any
    /// module registered a prefab patch routes those through XML too, where
    /// WidgetPrefabHook can inject. Cached after the first true (a registered
    /// patch never un-registers) so this hot getter stays a single bool check.
    /// </summary>
    public static void ConfigPostfix(ref bool __result)
    {
        try
        {
            if (__result) return;
            if (_anyPrefabPatch || UIExtenderEngine.Enabled.Any(r => r.Prefabs.Count > 0))
            {
                _anyPrefabPatch = true;
                __result = true;
            }
        }
        catch { /* never break prefab loading */ }
    }
}
