<#
  Build-Installer.ps1 -- assembles the BetaDeps All-in-One installer.

  What it does:
    1. Stages the FOUR BUTR dependency modules from dist\Modules into payload\Modules
       (the BetaDeps framework module itself is intentionally NOT bundled here).
    2. Stages BLSE's bin\Win64_Shipping_Client into payload\BLSE.
    3. Gathers license notices (BLSE MIT + BetaDeps third-party) into payload\LICENSES.
    4. Compiles BetaDeps-AllInOne.iss with Inno Setup (ISCC.exe) -> dist\BetaDeps-AllInOne-v<ver>.exe

  Prerequisites (one-time):
    - Inno Setup 6 installed (https://jrsoftware.org/isdl.php) -- provides ISCC.exe.
      (winget install JRSoftware.InnoSetup puts it under %LOCALAPPDATA%\Programs\Inno Setup 6.)
    - A copy of BLSE extracted somewhere, passed via -BlseDir. The folder you pass
      must contain  bin\Win64_Shipping_Client\Bannerlord.BLSE.LauncherEx.exe
      (download "Manual" BLSE from Nexus mod 1 or BUTR/Bannerlord.BLSE releases and
      unzip it; point -BlseDir at the unzipped root).
    - dist\Modules must exist (run scripts\Build-Phase1.ps1 first if it doesn't).

  Usage:
    cd C:\dev\modready\framework
    .\installer\Build-Installer.ps1 -BlseDir "C:\path\to\unzipped-BLSE" -Version 1.0.0
#>

param(
  [Parameter(Mandatory = $true)] [string] $BlseDir,
  [string] $Version = '1.0.0'
)

$ErrorActionPreference = 'Stop'
$Installer = $PSScriptRoot
$Repo      = Split-Path $Installer -Parent
$Dist      = Join-Path $Repo 'dist'
$Payload   = Join-Path $Installer 'payload'

function Fail($msg) { Write-Host "ERROR: $msg" -ForegroundColor Red; exit 1 }

# --- 1. sanity: clean module staging present ---------------------------------
# The all-in-one (ModReady) installer bundles BLSE + the FOUR BUTR dependency
# modules ONLY. The BetaDeps framework module itself (PatchShield/SaveShield/
# music picker, Modules\BetaDeps\) is intentionally NOT shipped here -- it is
# a separate mod. Note: BetaDeps.Foundation.dll still ships INSIDE each
# dependency module's bin -- it is their shared [ModuleInitializer] resolve-hook
# shim (+ DiagLog) and the four modules cannot load without it.
$Modules = Join-Path $Dist 'Modules'
$payloadModules = 'Bannerlord.Harmony','Bannerlord.UIExtenderEx','Bannerlord.ButterLib','Bannerlord.MBOptionScreen'
if (-not (Test-Path $Modules)) {
  Fail 'dist\Modules not found. Run ".\scripts\Build-Phase1.ps1" first to stage the modules.'
}
foreach ($m in $payloadModules) {
  if (-not (Test-Path (Join-Path $Modules $m))) { Fail "dist\Modules\$m is missing -- rebuild with Build-Phase1.ps1." }
}

# --- 2. sanity: BLSE source present ------------------------------------------
$BlseBin = Join-Path $BlseDir 'bin\Win64_Shipping_Client'
if (-not (Test-Path (Join-Path $BlseBin 'Bannerlord.BLSE.LauncherEx.exe'))) {
  Fail "BLSE not found at '$BlseBin'. Download the Manual BLSE zip, unzip it, and pass -BlseDir pointing at the unzipped root (the folder containing bin\Win64_Shipping_Client\Bannerlord.BLSE.LauncherEx.exe)."
}

# --- 3. (re)build payload ----------------------------------------------------
if (Test-Path $Payload) { Remove-Item $Payload -Recurse -Force }
New-Item -ItemType Directory -Path (Join-Path $Payload 'Modules')  | Out-Null
New-Item -ItemType Directory -Path (Join-Path $Payload 'BLSE')     | Out-Null
New-Item -ItemType Directory -Path (Join-Path $Payload 'LICENSES') | Out-Null

Write-Host 'Staging the four BUTR dependency modules (BetaDeps module folder excluded)...' -ForegroundColor Cyan
foreach ($m in $payloadModules) {
  Copy-Item (Join-Path $Modules $m) (Join-Path $Payload 'Modules') -Recurse -Force
}

Write-Host 'Staging BLSE binaries...' -ForegroundColor Cyan
Copy-Item (Join-Path $BlseBin '*') (Join-Path $Payload 'BLSE') -Recurse -Force

Write-Host 'Gathering license notices...' -ForegroundColor Cyan
# BLSE's own LICENSE (MIT, (c) BUTR) -- required notice. Try a few common spots.
$blseLicense = @(
  (Join-Path $BlseDir 'LICENSE'),
  (Join-Path $BlseDir 'LICENSE.txt'),
  (Join-Path $BlseBin 'LICENSE')
) | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $blseLicense) {
  Fail "BLSE LICENSE file not found in '$BlseDir'. MIT requires we ship its notice -- grab LICENSE from github.com/BUTR/Bannerlord.BLSE and place it in the BLSE folder."
}
Copy-Item $blseLicense (Join-Path $Payload 'LICENSES\BLSE-LICENSE.txt') -Force

# Third-party notices (MIT: 0Harmony, Mono.Cecil, MonoMod.*, Newtonsoft.Json) --
# these libs are bundled INSIDE the four dependency modules, so their notices are
# REQUIRED in the installer. The file is generated by Build-Phase1 into
# dist\Modules\BetaDeps\ (that folder is built even though we don't SHIP it).
# Hard-fail rather than silently drop: missing notices is a license-compliance
# gap, not a cosmetic one.
$btp = Join-Path $Modules 'BetaDeps\THIRD-PARTY-LICENSES.txt'
if (Test-Path $btp) {
  Copy-Item $btp (Join-Path $Payload 'LICENSES\BetaDeps-THIRD-PARTY-LICENSES.txt') -Force
} else {
  Fail "Third-party license notices not found at '$btp'. They are REQUIRED (Harmony/Cecil/MonoMod/Newtonsoft ship inside the dependency modules). Run .\scripts\Build-Phase1.ps1 first so dist\Modules\BetaDeps\THIRD-PARTY-LICENSES.txt exists."
}
# BetaDeps own license if present at repo root.
foreach ($lic in 'LICENSE','LICENSE.txt','LICENSE.md') {
  $p = Join-Path $Repo $lic
  if (Test-Path $p) { Copy-Item $p (Join-Path $Payload "LICENSES\BetaDeps-$lic") -Force; break }
}

# --- 4. find ISCC and compile -----------------------------------------------
$iscc = Get-Command ISCC.exe -ErrorAction SilentlyContinue
if ($iscc) {
  $iscc = $iscc.Source
} else {
  foreach ($c in @(
    "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
    "$env:ProgramFiles\Inno Setup 6\ISCC.exe",
    "$env:LOCALAPPDATA\Programs\Inno Setup 6\ISCC.exe")) {
    if (Test-Path $c) { $iscc = $c; break }
  }
}
if (-not $iscc) {
  Fail 'Inno Setup (ISCC.exe) not found. Install Inno Setup 6 from https://jrsoftware.org/isdl.php and re-run.'
}

Write-Host 'Compiling installer with Inno Setup...' -ForegroundColor Cyan
& $iscc "/DAppVersion=$Version" (Join-Path $Installer 'BetaDeps-AllInOne.iss')
if ($LASTEXITCODE -ne 0) { Fail "Inno Setup compile failed (exit $LASTEXITCODE)." }

Write-Host "Done. Installer written to dist\BetaDeps-AllInOne-v$Version.exe" -ForegroundColor Green
